apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: dev
  labels:
    app: inventory-service
spec:
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app: inventory-service
  type: LoadBalancer