version: '3.9'
services:
  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    networks:
      - coffee-shop-network
    environment: 
      - espresso-shot=10000
      - milk=1000
      - milk-foam=60000
      - hot-water=99999999
  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      - INVENTORY_URL=http://inventory-service:8082
    depends_on:
      - inventory-service
    networks:
      - coffee-shop-network

networks:
  coffee-shop-network:
    driver: bridge
